
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!

target 'SnowBallEngineDemo' do
  
  # 通过仓库内本地SDK文件夹中导入，一般是最新版本
	pod 'SnowBallEngine', :path => '../SDK/'
  # 通过Cocopods远程仓库导入，不一定是最新版本
#	pod 'SnowBallEngine', '~> 0.4'

  pod 'Google-Mobile-Ads-SDK'
	
end

post_install do |installer|
	installer.generated_projects.each do |project|
		project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
			xcconfig_path = config.base_configuration_reference.real_path
			xcconfig = File.read(xcconfig_path)
			xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
			File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
			end
		end
	end
end
